### ISSUE TITLE
sets of results

### ISSUE THREAD

**Issue by yocontra** [flaviodelbianco/mongoose-format-fields#2]
when doing a query like this, it would be cool to be able to call format on an array

``` js
User.find({}, function(err, users){
  res.send(users.format());
});
```

as sugar for

``` js
User.find({}, function(err, users){
  res.send(users.map(function(user){
    return user.format();
  });
});
```

**Comment by flaviodelbianco** [comment]
users is an array, it's impossible to add custom methods to an array

**Comment by contra** [comment]
![screen shot 2018-08-14 at 6 43 09 pm](https://user-images.githubusercontent.com/425716/44122445-e9721522-9ff1-11e8-882d-0ceeda217ba2.png)

Arrays are objects so you can do whatever you want with them - you can also make use of newer JS features to make custom objects that are iterable as arrays.

**Comment by contra** [comment]
Your call though - don't use this anymore (3yr old ticket) but just thought I would fill you in on that ^
